server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adeskdb?currentSchema=ticket
    username: adesk_admin
    password: adesk_password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: warn
    org.flywaydb.core: info
