CREATE TABLE IF NOT EXISTS outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id UUID NOT NULL,
    topic TEXT NOT NULL,
    record_key TEXT NOT NULL,
    payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_outbox_unpublished ON outbox (published_at) WHERE published_at IS NULL;
